legged_model:
  ubuntu:
  - ros-humble-legged-model
legged_estimation:
  ubuntu:
  - ros-humble-legged-estimation
legged_model_ros2:
  ubuntu:
  - ros-humble-legged-model-ros2
legged_controllers:
  ubuntu:
  - ros-humble-legged-controllers
message_logger:
  ubuntu:
  - ros-humble-message-logger
soem_rsl:
  ubuntu:
  - ros-humble-soem-rsl
soem_interface_rsl:
  ubuntu:
  - ros-humble-soem-interface-rsl
soem_interface_examples:
  ubuntu:
  - ros-humble-soem-interface-examples
soem_ros2:
  ubuntu:
  - ros-humble-soem-ros2
