name: Builder Humble

on:
  workflow_dispatch:
  push:
    paths:
      - ros2.repos
jobs:
  build_testing:
    runs-on: ubuntu-22.04
    steps:
      - uses: qiayuanl/ros-deb-builder-action@main
        with:
          DEB_DISTRO: jammy
          ROS_DISTRO: humble
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SQUASH_HISTORY: true
          REPOS_FILE: ros2.repos
  
