name: Builder

on:
  workflow_dispatch:
  push:

jobs:
  build_testing:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: qiayuanl/ecat_manager
          token: ${{ secrets.GH_PAT }}
          path: 'src/ecat_manager'
      - uses: actions/checkout@v2
        with:
          repository: qiayuanl/cleardrive
          token: ${{ secrets.GH_PAT }} 
          path: 'src/cleardrive'
      - uses: actions/checkout@v2
        with:
          repository: qiayuanl/mit_ecat
          token: ${{ secrets.GH_PAT }} 
          path: 'src/mit_ecat'
      - uses: actions/checkout@v2
        with:
          repository: qiayuanl/rm_ecat
          token: ${{ secrets.GH_PAT }} 
          path: 'src/rm_ecat'
      - run: pwd
      - run: ls
      - uses: qiayuanl/ros-deb-builder-action@main
        with:
          DEB_DISTRO: focal
          ROS_DISTRO: noetic
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SQUASH_HISTORY: true
          SKIP_CHECKOUT: true
          SKIP_PACKAGES: >-
            soem_interface_examples
            cleardrive_example
            rm_ecat_ros
